export const professionList = [
  "Software Engineer",
  "Doctor",
  "Teacher",
  "Designer",
  "Accountant",
  "Writer",
  "Chef",
  "Electrician",
  "Mechanic",
  "Artist",
  "Photographer",
  "Lawyer",
  "Marketing Manager",
  "Sales Representative",
  "Nurse",
  "Architect",
  "Police Officer",
  "Pilot",
  "Financial Analyst",
  "Data Scientist",
  "Other",
];
export const workExperienceList = [
  "Software Engineer",
  "Doctor",
  "Teacher",
  "Designer",
  "Accountant",
  "Writer",
  "Chef",
  "Electrician",
  "Mechanic",
  "Artist",
  "Photographer",
  "Lawyer",
  "Marketing Manager",
  "Sales Representative",
  "Nurse",
  "Architect",
  "Police Officer",
  "Pilot",
  "Financial Analyst",
  "Data Scientist",
  "Other",
];
